<a href="https://colab.research.google.com/github/vvrgit/AI-Projects/blob/main/ZCP_NTHD_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Mount Google Drive#

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


#Import Libraries#

In [2]:
# importing libraries  
import numpy as nm  
import matplotlib.pyplot as mtp  
import pandas as pd

#ZCP-Dataset-01#

#Load Data#

In [15]:
# load dataset
dataset03 = pd.read_csv("/content/drive/MyDrive/B.Tech Projects/2021-2022/ZCP/Noise-Data/ZCP-CSV/ZCP-NOISE-01.csv")
dataset03.head()

Slope  Intercept         R      RMSE  label
0  323.707793  -0.001276  0.985857  0.007952      1
1  278.334483   0.007161  0.965635  0.012121      0
2  295.054647   0.001057  0.969708  0.012389      0
3  296.718752   0.006121  0.968179  0.011155      0
4  506.344807  -0.102235  0.937057  0.041172      0

#Data Normalization#

In [16]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
data = scaler.fit_transform(dataset03)
data

array([[0.62538848, 0.53316552, 0.99298461, 0.03573802, 1.        ],
       [0.60080565, 0.53321943, 0.98278046, 0.06052042, 0.        ],
       [0.60986448, 0.53318042, 0.98483585, 0.06211258, 0.        ],
       ...,
       [0.66110217, 0.28435546, 0.99507448, 0.09873651, 0.        ],
       [0.64606721, 0.30202947, 0.99536012, 0.05545617, 0.        ],
       [0.62252113, 0.32973938, 0.99833388, 0.0117413 , 1.        ]])

#Data Split#

In [17]:
from sklearn.model_selection import train_test_split
df_train, df_test = train_test_split(data, train_size = 0.7, test_size = 0.3, random_state = 100)

In [18]:
y_train = df_train[:,4]
X_train = df_train[:,0:4]
y_test = df_test[:,4]
X_test = df_test[:,0:4]

#Random Forest Model#

In [ ]:
#Fitting Decision Tree classifier to the training set  
from sklearn.ensemble import RandomForestClassifier  
classifier= RandomForestClassifier(n_estimators= 1, criterion="entropy")  #criterion="gini"
classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=1)

In [ ]:
#Predicting the test set result  
y_pred_test= classifier.predict(X_test)
y_pred_train= classifier.predict(X_train)

In [ ]:
from sklearn import metrics #Import scikit-learn metrics module for accuracy calculation
print("Testing Accuracy:",metrics.accuracy_score(y_test, y_pred_test))
print("Training Accuracy:",metrics.accuracy_score(y_train, y_pred_train))

Testing Accuracy: 0.9933333333333333
Training Accuracy: 0.9928263988522238


#Logistic Regression Model#

In [19]:
from sklearn.linear_model import LogisticRegression
lr_model = LogisticRegression()
lr_model.fit(X_train,y_train)

LogisticRegression()

In [20]:
#Predicting the test set result  
y_pred_test= lr_model.predict(X_test)
y_pred_train= lr_model.predict(X_train)

In [21]:
from sklearn import metrics #Import scikit-learn metrics module for accuracy calculation
print("Testing Accuracy:",metrics.accuracy_score(y_test, y_pred_test))
print("Training Accuracy:",metrics.accuracy_score(y_train, y_pred_train))

Testing Accuracy: 0.9533333333333334
Training Accuracy: 0.9526542324246772


In [22]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred_test)

array([[286,   0],
       [ 14,   0]])

In [23]:
confusion_matrix(y_train, y_pred_train)

array([[664,   0],
       [ 33,   0]])

In [24]:
import pickle
# Save the model
filename = 'LGR.pkl'
pickle.dump(lr_model, open(filename, 'wb'))

In [25]:
filename = 'LGR.pkl'
loaded_model = pickle.load(open(filename, 'rb'))
result = loaded_model.predict(X_test)
result

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [26]:
# load dataset
dataset_test = pd.read_excel("/content/drive/MyDrive/B.Tech Projects/2021-2022/ZCP/Result Analysis/Noise/Testsignal.xlsx")
dataset_test.head()

m         c         r         e  l
0  323.707793 -0.001276  0.985857  0.007952  1
1  598.980836 -0.172329  0.977641  0.053721  0
2  330.918134 -0.006196  0.705578  0.052829  0
3  529.666009 -0.348752  0.968744  0.059864  0
4  411.740579 -0.238543  0.735847  0.066133  0

In [28]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
data = scaler.fit_transform(dataset_test)
data

array([[0.76072854, 0.47080851, 0.99346687, 0.03597133, 1.        ],
       [1.        , 0.45945448, 0.98925174, 0.37724787, 0.        ],
       [0.76699588, 0.47048192, 0.8496702 , 0.3705947 , 0.        ],
       [0.93975051, 0.44774397, 0.98468738, 0.4230539 , 0.        ],
       [0.83724796, 0.45505937, 0.86519998, 0.46980162, 0.        ],
       [0.39813207, 0.53822898, 0.25052258, 0.35778124, 0.        ],
       [0.0740169 , 0.62008007, 0.09181539, 0.99761759, 0.        ],
       [0.17017112, 0.61983707, 0.24033465, 0.82196617, 0.        ],
       [0.46313603, 0.53957523, 0.48345769, 0.30574313, 0.        ],
       [0.81200428, 0.42101241, 0.96080287, 0.53844089, 0.        ],
       [0.50810035, 0.52152699, 0.39283052, 0.59597996, 0.        ],
       [0.38991984, 0.57715938, 0.544401  , 0.65954554, 0.        ],
       [0.88698564, 0.34209568, 0.        , 0.66898718, 0.        ],
       [0.70077771, 0.41359121, 0.29674219, 0.84016317, 0.        ],
       [0.30160378, 0.61979183, 0.

In [33]:
X_test_signal=data[:,0:4]
X_test_signal

array([[0.76072854, 0.47080851, 0.99346687, 0.03597133],
       [1.        , 0.45945448, 0.98925174, 0.37724787],
       [0.76699588, 0.47048192, 0.8496702 , 0.3705947 ],
       [0.93975051, 0.44774397, 0.98468738, 0.4230539 ],
       [0.83724796, 0.45505937, 0.86519998, 0.46980162],
       [0.39813207, 0.53822898, 0.25052258, 0.35778124],
       [0.0740169 , 0.62008007, 0.09181539, 0.99761759],
       [0.17017112, 0.61983707, 0.24033465, 0.82196617],
       [0.46313603, 0.53957523, 0.48345769, 0.30574313],
       [0.81200428, 0.42101241, 0.96080287, 0.53844089],
       [0.50810035, 0.52152699, 0.39283052, 0.59597996],
       [0.38991984, 0.57715938, 0.544401  , 0.65954554],
       [0.88698564, 0.34209568, 0.        , 0.66898718],
       [0.70077771, 0.41359121, 0.29674219, 0.84016317],
       [0.30160378, 0.61979183, 0.74098496, 0.3676402 ],
       [0.5009288 , 0.49957153, 0.44440848, 0.4556033 ],
       [0.09252584, 0.75067864, 0.92485382, 0.39015609],
       [0.08124584, 0.7620671 ,

In [35]:
y_pred_test_signal= lr_model.predict(X_test_signal)
y_pred_test_signal

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0.])

#Decision Tree#

In [ ]:
from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier

In [ ]:
# Create Decision Tree classifer object
clf = DecisionTreeClassifier(criterion="entropy", max_depth=12)
# Train Decision Tree Classifer
clf = clf.fit(X_train,y_train)
clf.get_depth()

12

In [ ]:
#Predicting the test set result  
y_pred_test= clf.predict(X_test)
y_pred_train= clf.predict(X_train)

In [ ]:
from sklearn import metrics #Import scikit-learn metrics module for accuracy calculation
print("Testing Accuracy:",metrics.accuracy_score(y_test, y_pred_test))
print("Training Accuracy:",metrics.accuracy_score(y_train, y_pred_train))

Testing Accuracy: 0.9833333333333333
Training Accuracy: 1.0


In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred_test)

array([[289,   4],
       [  1,   6]])

In [ ]:
confusion_matrix(y_train, y_pred_train)

array([[682,   0],
       [  0,  15]])